import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { withRateLimit } from "@/lib/rate-limit";

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ token: string }> }
) {
  const { token } = await params;
  const ip =
    request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ||
    request.headers.get("x-real-ip") ||
    "anon";

  return withRateLimit(
    `public-report:${token || "empty"}:${ip}`,
    async () => {
      const report = await prisma.weeklyReport.findFirst({
        where: { shareToken: token, shareEnabled: true, status: "READY" },
        select: {
          id: true,
          periodStart: true,
          periodEnd: true,
          reportType: true,
          frequency: true,
          executiveSummary: true,
          payload: true,
          aiUsed: true,
          createdAt: true,
          user: { select: { name: true, username: true } },
        },
      });

      if (!report) {
        return NextResponse.json({ error: "Report not found" }, { status: 404 });
      }

      return NextResponse.json({
        report: {
          ...report,
          branding:
            "Weekly website intelligence report generated by WatchFlowing",
        },
      });
    },
    null,
    "public"
  );
}
