import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { withRateLimit } from "@/lib/rate-limit";
import { trackEvent } from "@/lib/analytics";

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ token: string }> }
) {
  const { token } = await params;
  const ip =
    request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ||
    request.headers.get("x-real-ip") ||
    "anon";

  return withRateLimit(
    `public-report:${token || "empty"}:${ip}`,
    async () => {
      const report = await prisma.weeklyReport.findFirst({
        where: { shareToken: token, shareEnabled: true, status: "READY" },
        select: {
          id: true,
          periodStart: true,
          periodEnd: true,
          reportType: true,
          frequency: true,
          executiveSummary: true,
          payload: true,
          aiUsed: true,
          createdAt: true,
          user: {
            select: {
              name: true,
              username: true,
              agencyModeEnabled: true,
              agencyBrandName: true,
              agencyShowPoweredBy: true,
            },
          },
        },
      });

      if (!report) {
        return NextResponse.json({ error: "Report not found" }, { status: 404 });
      }

      void trackEvent({
        type: "report_shared",
        metadata: {
          reportId: report.id,
          view: "public",
          referer: request.headers.get("referer"),
        },
      });

      const agency = report.user.agencyModeEnabled;
      const brand =
        agency && report.user.agencyBrandName?.trim()
          ? report.user.agencyBrandName.trim()
          : null;
      const showPoweredBy = !agency || report.user.agencyShowPoweredBy;

      return NextResponse.json({
        report: {
          ...report,
          displayBrand: brand,
          showPoweredBy,
          branding: brand
            ? `Prepared for clients by ${brand}`
            : "Weekly website intelligence report generated by WatchFlowing AI",
          cta: {
            label: "Create your own monitoring report",
            href: "/sign-up?from=report",
          },
        },
      });
    },
    null,
    "public"
  );
}
