import { Resend } from "resend";
import { classifyEmailSendError } from "@/lib/notifications/email";

let resend: Resend | null = null;

function getResend(): Resend {
  if (!resend) {
    const apiKey = process.env.RESEND_API_KEY?.trim();
    if (!apiKey) throw new Error("Missing configuration: RESEND_API_KEY");
    resend = new Resend(apiKey);
  }
  return resend;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export async function sendWeeklyReportEmail(params: {
  to: string;
  name?: string | null;
  periodLabel: string;
  executiveSummary: string;
  totalChanges: number;
  importantCount: number;
  importantChanges: Array<{ title: string; summary: string; importance: string }>;
  recommendations: string[];
  reportUrl: string;
}) {
  if (!params.to?.trim()) {
    throw new Error("Missing configuration: recipient email address");
  }

  const from =
    process.env.RESEND_FROM_EMAIL?.trim() ||
    "WatchFlowing Notifications <notifications@watchflowing.com>";
  const greeting = params.name ? `Hi ${escapeHtml(params.name)},` : "Hi,";

  const importantHtml = params.importantChanges.length
    ? params.importantChanges
        .map(
          (c) =>
            `<tr><td style="padding:10px 0;border-bottom:1px solid #1f1f1f;">
              <div style="font-size:12px;color:#fbbf24;text-transform:uppercase;letter-spacing:0.08em;">${escapeHtml(c.importance)}</div>
              <div style="font-size:15px;color:#f4f4f5;font-weight:600;margin-top:4px;">${escapeHtml(c.title)}</div>
              <div style="font-size:13px;color:#a1a1aa;margin-top:4px;line-height:1.5;">${escapeHtml(c.summary)}</div>
            </td></tr>`
        )
        .join("")
    : `<tr><td style="padding:10px 0;color:#71717a;font-size:13px;">No high-priority changes this period.</td></tr>`;

  const recHtml = params.recommendations
    .map(
      (r) =>
        `<li style="margin:0 0 8px;color:#d4d4d8;font-size:13px;line-height:1.5;">${escapeHtml(r)}</li>`
    )
    .join("");

  const html = `<!DOCTYPE html>
<html><body style="margin:0;background:#090909;font-family:Inter,Segoe UI,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#090909;padding:32px 12px;">
    <tr><td align="center">
      <table width="560" cellpadding="0" cellspacing="0" style="max-width:560px;background:#0c0c0c;border:1px solid #1f1f1f;border-radius:16px;overflow:hidden;">
        <tr><td style="padding:28px 28px 16px;border-bottom:1px solid #1f1f1f;">
          <div style="font-size:11px;letter-spacing:0.2em;text-transform:uppercase;color:#22d3ee;">WatchFlowing</div>
          <h1 style="margin:10px 0 0;font-size:22px;color:#fafafa;font-weight:600;">Weekly Intelligence Report</h1>
          <p style="margin:8px 0 0;color:#71717a;font-size:13px;">${escapeHtml(params.periodLabel)}</p>
        </td></tr>
        <tr><td style="padding:24px 28px;">
          <p style="margin:0 0 12px;color:#d4d4d8;font-size:14px;">${greeting}</p>
          <p style="margin:0;color:#a1a1aa;font-size:14px;line-height:1.6;">Your websites this week — WatchFlowing kept watching even while you were away.</p>
          <div style="margin:20px 0;padding:16px;border-radius:12px;background:#111;border:1px solid #1f2937;">
            <p style="margin:0;color:#f4f4f5;font-size:15px;line-height:1.55;font-weight:500;">${escapeHtml(params.executiveSummary)}</p>
            <p style="margin:12px 0 0;font-size:12px;color:#71717a;">${params.totalChanges} changes · ${params.importantCount} need attention</p>
          </div>
          <h2 style="margin:0 0 8px;font-size:13px;letter-spacing:0.12em;text-transform:uppercase;color:#22d3ee;">Important changes</h2>
          <table width="100%" cellpadding="0" cellspacing="0">${importantHtml}</table>
          <h2 style="margin:24px 0 8px;font-size:13px;letter-spacing:0.12em;text-transform:uppercase;color:#22d3ee;">Recommendations</h2>
          <ul style="padding-left:18px;margin:0;">${recHtml}</ul>
          <div style="margin:28px 0 8px;text-align:center;">
            <a href="${escapeHtml(params.reportUrl)}" style="display:inline-block;padding:12px 22px;border-radius:999px;background:#0891b2;color:#041016;text-decoration:none;font-weight:600;font-size:14px;">Open full report</a>
          </div>
        </td></tr>
        <tr><td style="padding:16px 28px 24px;border-top:1px solid #1f1f1f;">
          <p style="margin:0;color:#52525b;font-size:11px;text-align:center;">Generated by WatchFlowing AI · You can manage report preferences in Settings.</p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body></html>`;

  const text = [
    "WatchFlowing Weekly Intelligence Report",
    params.periodLabel,
    "",
    params.executiveSummary,
    `${params.totalChanges} changes · ${params.importantCount} need attention`,
    "",
    "Open full report:",
    params.reportUrl,
  ].join("\n");

  try {
    const result = await getResend().emails.send({
      from,
      to: params.to,
      subject: "Your WatchFlowing Weekly Intelligence Report",
      html,
      text,
    });

    if (result.error) {
      throw new Error(result.error.message || "Resend API rejected the request");
    }
  } catch (err) {
    throw new Error(classifyEmailSendError(err));
  }
}
