import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { withRateLimit } from "@/lib/rate-limit";

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ token: string }> }
) {
  const { token } = await params;
  const ip =
    request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ||
    request.headers.get("x-real-ip") ||
    "anon";

  return withRateLimit(
    `public-score:${token || "x"}:${ip}`,
    async () => {
      const row = await prisma.intelligenceScore.findFirst({
        where: { shareToken: token },
      });
      if (!row) {
        return NextResponse.json({ error: "Not found" }, { status: 404 });
      }

      const payload = row.payload as Record<string, unknown>;
      return NextResponse.json({
        score: {
          id: row.id,
          url: row.url,
          hostname: row.hostname,
          overallScore: row.overallScore,
          createdAt: row.createdAt,
          payload,
          branding: "Website intelligence snapshot generated by WatchFlowing AI",
        },
      });
    },
    null,
    "public"
  );
}
