"use client";

import { use, useEffect, useState } from "react";
import Link from "next/link";
import { Loader2, Sparkles } from "lucide-react";
import type { WeeklyReportPayload } from "@/lib/reports/types";

export default function PublicReportPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = use(params);
  const [data, setData] = useState<{
    executiveSummary: string;
    payload: WeeklyReportPayload;
    branding: string;
    displayBrand?: string | null;
    showPoweredBy?: boolean;
    cta?: { label: string; href: string };
    periodStart: string;
    periodEnd: string;
    user?: { name: string | null; username: string | null };
  } | null>(null);
  const [error, setError] = useState(false);

  useEffect(() => {
    fetch(`/api/public/report/${token}`)
      .then(async (r) => {
        if (!r.ok) throw new Error("missing");
        return r.json();
      })
      .then((json) => {
        setData({
          executiveSummary: json.report.executiveSummary,
          payload: json.report.payload,
          branding: json.report.branding,
          displayBrand: json.report.displayBrand,
          showPoweredBy: json.report.showPoweredBy,
          cta: json.report.cta,
          periodStart: json.report.periodStart,
          periodEnd: json.report.periodEnd,
          user: json.report.user,
        });
      })
      .catch(() => setError(true));
  }, [token]);

  if (error) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-[#090909] px-4 text-zinc-400">
        This report is private or no longer available.
      </div>
    );
  }

  if (!data) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-[#090909]">
        <Loader2 className="h-6 w-6 animate-spin text-cyan-400" />
      </div>
    );
  }

  const p = data.payload;
  const titleBrand =
    data.displayBrand || data.user?.name || data.user?.username || "Team";

  return (
    <div className="min-h-screen bg-[#090909] text-zinc-200">
      <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(ellipse_at_top,rgba(34,211,238,0.08),transparent_55%)]" />
      <div className="relative mx-auto max-w-3xl px-4 py-10 sm:py-14">
        <div className="mb-8 flex items-center justify-between">
          <Link href="/" className="text-xs text-zinc-500 hover:text-cyan-300">
            WatchFlowing
          </Link>
          <p className="font-mono text-[10px] uppercase tracking-widest text-zinc-600">
            Shared intelligence
          </p>
        </div>

        <article className="rounded-2xl border border-white/[0.08] bg-[#0c0c0c]/90 p-6 shadow-[0_40px_120px_-60px_rgba(34,211,238,0.35)] sm:p-8">
          <div className="flex items-center gap-2 text-cyan-400">
            <Sparkles className="h-4 w-4" />
            <p className="font-mono text-[10px] uppercase tracking-[0.25em]">
              Generated by WatchFlowing AI
            </p>
          </div>
          <h1 className="mt-2 text-2xl font-semibold tracking-tight text-zinc-50 sm:text-3xl">
            {titleBrand} — Weekly Report
          </h1>
          <p className="mt-1 text-sm text-zinc-500">{p.periodLabel}</p>

          <div className="mt-6 grid grid-cols-2 gap-2 sm:grid-cols-4">
            {[
              ["Changes", p.stats.totalChanges],
              ["Attention", p.stats.importantCount],
              ["Active", p.stats.monitorsActive],
              ["Errors", p.stats.monitorsError],
            ].map(([label, value]) => (
              <div
                key={String(label)}
                className="rounded-xl border border-white/[0.06] bg-black/30 px-3 py-3"
              >
                <p className="font-mono text-[9px] uppercase tracking-wider text-zinc-600">
                  {label}
                </p>
                <p className="mt-1 font-mono text-xl text-zinc-100">{value}</p>
              </div>
            ))}
          </div>

          <div className="mt-6 rounded-xl border border-cyan-500/20 bg-cyan-500/[0.06] p-4">
            <p className="font-mono text-[10px] uppercase tracking-widest text-cyan-500/80">
              Executive summary
            </p>
            <p className="mt-2 text-[15px] leading-relaxed text-zinc-100">
              {data.executiveSummary}
            </p>
          </div>

          <section className="mt-8">
            <h2 className="text-sm font-medium text-zinc-200">Detected changes</h2>
            <div className="mt-3 space-y-2">
              {p.importantChanges.length === 0 ? (
                <p className="text-sm text-zinc-500">No high-priority changes this period.</p>
              ) : (
                p.importantChanges.map((c) => (
                  <div
                    key={c.changeId}
                    className="rounded-xl border border-white/[0.06] bg-black/20 p-3"
                  >
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="font-mono text-[9px] uppercase text-amber-300/90">
                        {c.importance}
                      </span>
                      <p className="text-sm font-medium text-zinc-100">{c.monitorName}</p>
                    </div>
                    <p className="mt-1 text-xs leading-relaxed text-zinc-400">{c.summary}</p>
                    <p className="mt-1 truncate font-mono text-[10px] text-zinc-600">
                      {c.monitorUrl}
                    </p>
                  </div>
                ))
              )}
            </div>
          </section>

          <section className="mt-8 grid gap-4 sm:grid-cols-2">
            <div className="rounded-xl border border-white/[0.06] p-4">
              <h2 className="text-sm font-medium text-zinc-200">Website health</h2>
              <ul className="mt-3 space-y-2">
                {p.unresolvedIssues.map((line) => (
                  <li key={line} className="text-xs leading-relaxed text-zinc-400">
                    • {line}
                  </li>
                ))}
              </ul>
            </div>
            <div className="rounded-xl border border-white/[0.06] p-4">
              <h2 className="text-sm font-medium text-zinc-200">Recommendations</h2>
              <ul className="mt-3 space-y-2">
                {p.recommendations.map((r) => (
                  <li key={r} className="text-xs leading-relaxed text-zinc-400">
                    • {r}
                  </li>
                ))}
              </ul>
            </div>
          </section>

          <div className="mt-10 rounded-2xl border border-cyan-400/20 bg-gradient-to-br from-cyan-500/10 to-transparent p-5 text-center">
            <p className="text-sm font-medium text-zinc-100">
              {data.cta?.label ?? "Create your own monitoring report"}
            </p>
            <p className="mt-1 text-xs text-zinc-500">
              WatchFlowing watches your sites and explains what matters — even when you are away.
            </p>
            <Link
              href={`${data.cta?.href ?? "/sign-up?from=report"}&ref_source=public_report`}
              className="mt-4 inline-flex min-h-11 items-center rounded-full border border-cyan-400/30 bg-cyan-500/20 px-5 text-sm font-medium text-cyan-50 hover:bg-cyan-500/30"
              onClick={() => {
                try {
                  localStorage.setItem("wf_signup_source", "public_report");
                } catch {
                  /* ignore */
                }
              }}
            >
              Start free monitoring
            </Link>
          </div>

          <footer className="mt-8 border-t border-white/[0.06] pt-5 text-center">
            <p className="text-xs text-zinc-600">{data.branding}</p>
            {data.showPoweredBy !== false && (
              <p className="mt-1 text-[11px] text-zinc-700">Powered by WatchFlowing</p>
            )}
          </footer>
        </article>
      </div>
    </div>
  );
}
