"use client";

import { useMemo, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Check, Copy, Share2 } from "lucide-react";
import { cn } from "@/lib/utils";

export type ShareableInsight = {
  monitorName: string;
  monitorUrl: string;
  summary: string;
  importance: string;
  bulletPoints: string[];
  createdAt: string;
  emoji?: string;
};

function buildReportText(insight: ShareableInsight): string {
  const bullets =
    insight.bulletPoints.length > 0
      ? insight.bulletPoints.map((b) => `• ${b}`).join("\n")
      : "• Review the detected change in WatchFlowing";

  return [
    `${insight.emoji ?? "📡"} WatchFlowing AI Report`,
    "",
    `Website: ${insight.monitorName}`,
    `URL: ${insight.monitorUrl}`,
    `Importance: ${insight.importance}`,
    `Detected: ${new Date(insight.createdAt).toLocaleString()}`,
    "",
    "Summary",
    insight.summary,
    "",
    "What changed / recommendations",
    bullets,
    "",
    "—",
    "Generated by WatchFlowing AI",
    "https://watchflowing.com",
  ].join("\n");
}

export function ShareInsightButton({
  insight,
  className,
}: {
  insight: ShareableInsight;
  className?: string;
}) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const report = useMemo(() => buildReportText(insight), [insight]);

  async function copyReport() {
    await navigator.clipboard.writeText(report);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 2000);
  }

  async function nativeShare() {
    if (typeof navigator !== "undefined" && navigator.share) {
      try {
        await navigator.share({
          title: `WatchFlowing AI · ${insight.monitorName}`,
          text: report,
        });
        return;
      } catch {
        // fall through to modal
      }
    }
    setOpen(true);
  }

  return (
    <>
      <button
        type="button"
        onClick={() => void nativeShare()}
        className={cn(
          "inline-flex min-h-11 items-center gap-2 rounded-full border border-white/[0.08] bg-white/[0.03] px-4 text-xs font-medium text-zinc-300 transition-colors hover:border-cyan-400/25 hover:bg-cyan-500/[0.06] hover:text-cyan-100",
          className
        )}
      >
        <Share2 className="h-3.5 w-3.5" />
        Share AI report
      </button>

      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-4 backdrop-blur-sm sm:items-center"
            onClick={() => setOpen(false)}
          >
            <motion.div
              initial={{ opacity: 0, y: 16, scale: 0.98 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: 12, scale: 0.98 }}
              transition={{ type: "spring", stiffness: 380, damping: 28 }}
              onClick={(e) => e.stopPropagation()}
              className="w-full max-w-lg rounded-2xl border border-white/[0.08] bg-[#0c0c0c] p-5 shadow-2xl"
            >
              <div className="flex items-start justify-between gap-3">
                <div>
                  <p className="font-mono text-[10px] uppercase tracking-[0.25em] text-cyan-500/70">
                    Shareable insight
                  </p>
                  <h3 className="mt-1 text-lg font-semibold text-zinc-100">
                    Generated by WatchFlowing AI
                  </h3>
                </div>
                <button
                  type="button"
                  onClick={() => setOpen(false)}
                  className="min-h-10 rounded-lg px-3 text-xs text-zinc-500 hover:text-zinc-300"
                >
                  Close
                </button>
              </div>

              <pre className="mt-4 max-h-[40vh] overflow-y-auto whitespace-pre-wrap break-words rounded-xl border border-white/[0.06] bg-black/40 p-4 font-mono text-[11px] leading-relaxed text-zinc-400">
                {report}
              </pre>

              <div className="mt-4 flex flex-wrap gap-2">
                <button
                  type="button"
                  onClick={() => void copyReport()}
                  className="inline-flex min-h-11 flex-1 items-center justify-center gap-2 rounded-full border border-cyan-400/30 bg-cyan-500/15 px-4 text-sm font-medium text-cyan-100 transition-colors hover:bg-cyan-500/25"
                >
                  {copied ? (
                    <>
                      <Check className="h-4 w-4 text-emerald-300" />
                      Copied
                    </>
                  ) : (
                    <>
                      <Copy className="h-4 w-4" />
                      Copy report
                    </>
                  )}
                </button>
              </div>
              <p className="mt-3 text-center text-[11px] text-zinc-600">
                Perfect for agencies, clients, and team updates.
              </p>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}
